### ISSUE TITLE
AppMap progression release

### ISSUE THREAD

**Issue by dustinbyrne** [applandinc/vscode-appland#208]
# AppMap progression walkthrough and metrics

### Metrics
- [ ] [`appmap.config`](https://github.com/applandinc/vscode-appland/issues/235)
- [x] [`appmap.data`](https://github.com/applandinc/vscode-appland/issues/229) (PR #231)
- [ ] [`appmap.project`](https://github.com/applandinc/vscode-appland/issues/230). (PR #240)

### Properties
- [ ] [`appmap.config`](https://github.com/applandinc/vscode-appland/issues/228)
- [ ] [`appmap.file`](https://github.com/applandinc/vscode-appland/issues/225)
- [ ] [`appmap.version_control`](https://github.com/applandinc/vscode-appland/issues/226)
- [ ] [`appmap.project`](https://github.com/applandinc/vscode-appland/issues/227)

### Events
- [ ] [`appland.appmap/plugin:install`](https://github.com/applandinc/vscode-appland/issues/209)
- [ ] [`appland.appmap/plugin:uninstall`](https://github.com/applandinc/vscode-appland/issues/210)
- [ ] [`appland.appmap/plugin/appmap:open`](https://github.com/applandinc/vscode-appland/issues/211)
- [ ] [`appland.appmap/plugin/appmap:upload`](https://github.com/applandinc/vscode-appland/issues/212)
- [ ] [`appland.appmap/plugin/remote_recording:start`](https://github.com/applandinc/vscode-appland/issues/213)
- [ ] [`appland.appmap/plugin/remote_recording:stop`](https://github.com/applandinc/vscode-appland/issues/214)
- [ ] [`appland.appmap/plugin/remote_recording:status`](https://github.com/applandinc/vscode-appland/issues/215)
- [ ] [`appland.appmap/project:open`](https://github.com/applandinc/vscode-appland/issues/216)
- [ ] [`appland.appmap/project/appmaps:write`](https://github.com/applandinc/vscode-appland/issues/217)
- [ ] [`appland.appmap/project/appmaps:delete`](https://github.com/applandinc/vscode-appland/issues/218)
- [ ] [`appland.appmap/project/config:write`](https://github.com/applandinc/vscode-appland/issues/219)
- [ ] [`appland.appmap/project/config:delete`](https://github.com/applandinc/vscode-appland/issues/220)
- [ ] [`appland.appmap/project/label:add`](https://github.com/applandinc/vscode-appland/issues/221)
- [ ] [`appland.appmap/project/label:remove`](https://github.com/applandinc/vscode-appland/issues/222)
- [ ] [`appland.appmap/project/dependency:add`](https://github.com/applandinc/vscode-appland/issues/223)
- [ ] [`appland.appmap/project/dependency:remove`](https://github.com/applandinc/vscode-appland/issues/224)
- [ ] [`appland.appmap/version_control:commit_file`](https://github.com/applandinc/vscode-appland/issues/206)
- [ ] [`appland.appmap/version_control:ignore_file`](https://github.com/applandinc/vscode-appland/issues/207)
- [ ] [`appland.appmap/version_control:untrack_file`](https://github.com/applandinc/vscode-appland/issues/205)

## End-user UI
TBD.
